# Generated by Django 4.1.7 on 2023-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default='', max_length=100)),
                ('song_artist', models.CharField(default='', max_length=100)),
                ('song_album', models.CharField(default='', max_length=100)),
                ('song_genre', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['song_genre'],
            },
        ),
    ]
